global: &global
    INFO_ALLOURIDEAS_EMAIL: info@example.org
    INFO_PHOTOCRACY_EMAIL: info@example.com
    SIGNUPS_ALLOURIDEAS_EMAIL: signups@example.org
    SIGNUPS_PHOTOCRACY_EMAIL: signups@example.com
    ERRORS_EMAIL: errors@example.org

production:
    <<: *global
    HOST: <%= ENV['ALLOURIDEAS_HOST'] %>
    API_HOST: <%= ENV['API_HOST'] %>
    PAIRWISE_USERNAME: <%= ENV['PAIRWISE_USERNAME'] %>
    PAIRWISE_PASSWORD: <%= ENV['PAIRWISE_PASSWORD'] %>
    IP_ADDR_HASH_SALT: <%= ENV['IP_ADDR_HASH_SALT'] %> #prevent dictionary attacks on stored ip address hashes

    PHOTOCRACY_USERNAME: <%= ENV['PHOTOCRACY_USERNAME'] %>
    PHOTOCRACY_PASSWORD: <%= ENV['PHOTOCRACY_PASSWORD'] %>
    PHOTOCRACY_HOST: photocracy.org

    INFO_ALLOURIDEAS_EMAIL: <%= ENV['INFO_ALLOURIDEAS_EMAIL'] %>
    INFO_PHOTOCRACY_EMAIL: <%= ENV['INFO_PHOTOCRACY_EMAIL'] %>
    SIGNUPS_ALLOURIDEAS_EMAIL: <%= ENV['SIGNUPS_ALLOURIDEAS_EMAIL'] %>
    SIGNUPS_PHOTOCRACY_EMAIL: <%= ENV['SIGNUPS_PHOTOCRACY_EMAIL'] %>
    ERRORS_EMAIL: <%= ENV['ERRORS_EMAIL'] %>
    SURVEY_SESSION_SECRET: <%= ENV['SURVEY_SESSION_SECRET'] %>
    BASE_SESSION_SECRET: <%= ENV['BASE_SESSION_SECRET'] %>

