# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development: &default
  adapter: mysql2
  user: root
  database: rebirth_development
  pool: 5
  timeout: 5000

production:
  <<: *default
  username: root
  password: <% ENV['SQL_DB_PASSWORD'] %>
  database: pairwise_production
  #host: localhost
  host: 127.0.0.1

