# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

production: 
  adapter: mysql2
  user: root
  pool: 5
  timeout: 5000
  username: root
  password: <%= ENV['SQL_DB_PASSWORD'] %>
  database: pairwise_production
  #host: localhost
  host: 127.0.0.1

