#!/usr/bin/env ruby

require 'logger'

logfile = File.open('log/PW_delayed_job_env.log', 'a')
my_logger = Logger.new(logfile)
my_logger.info $PROGRAM_NAME
my_logger.info '     '
my_logger.info ENV
my_logger.info '     '

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require 'delayed/command'
Delayed::Command.new(ARGV).daemonize
